### ISSUE TITLE
Themes allow setting of non-existent properties

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#5106]
### Describe the bug, what's wrong, and what you expected.

I found a bug (that I introduced in #4516). The themes are supposed to prevent setting of properties that don't exist. #4516 (found via a git bisect) introduced a bug where this is no longer handled and users can set theme options that don't exist. Making typos silently fail:

The following should error because the property is `show_scalar_bar` not `show_scalar_bars`:

```py
import pyvista as pv
pv.global_theme.show_scalar_bars = False
```

### Steps to reproduce the bug.

Current version of PyVista

```python
>>> import pyvista as pv
>>> pv.global_theme.foo = 0  # expect an AttributeError
>>>
```

Previous versions of PyVista: 

```py
>>> import pyvista as pv
>>> pv.global_theme.foo = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DefaultTheme' object has no attribute 'foo'
>>>
```

### System Information

```shell
main branch
```

**Comment by banesullivan** [comment]
What's even more odd is that this is tested by `test_theme_slots` in `tests/plotting/test_theme.py` and it works as expected there.

**Comment by banesullivan** [comment]
It might be an issue with subclasses:

```py
>>> import pyvista as pv
>>> theme = pv.plotting.themes.Theme()
>>> theme.foo = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Theme' object has no attribute 'foo'
>>> theme = pv.plotting.themes.DocumentTheme()
>>> theme.foo = 0
>>>
```

**Comment by banesullivan** [comment]
Aha! Going back to release v0.38 (before the commit that git-biset found), we can see this issue with subclasses existed previously too:

```py
git checkout v0.38.0
Note: switching to 'v0.38.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at badb694e Version 0.38.0
(vis) ➜  pyvista git:(v0.38.0) ✗ python
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> theme = pv.themes.DefaultTheme()
>>> theme.foo = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DefaultTheme' object has no attribute 'foo'
>>> theme = pv.themes.DocumentTheme()
>>> theme.foo = 0
>>>

**Comment by banesullivan** [comment]
TIL, `__slots__` are not inherited by subclasses:  https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots

> The action of a __slots__ declaration is not limited to the class where it is defined. __slots__ declared in parents are available in child classes. However, child subclasses will get a [__dict__](https://docs.python.org/3/library/stdtypes.html#object.__dict__) and __weakref__ unless they also define __slots__ (which should only contain names of any additional slots).

I'm not sure how to proceed here...

**Comment by MatthewFlamm** [comment]
This looks like it might would work, but I'm not sure.  https://stackoverflow.com/questions/56579348/how-can-i-force-subclasses-to-have-slots

**Comment by MatthewFlamm** [comment]
Whatever solution is come up with should also be extended to all the nested themes like  `pv.global_theme.lighting_params.interpolation`.

**Comment by MatthewFlamm** [comment]
I tried to fix this on #5112, but the overall machinery of `Theme` is problematic.  Specifically around the subclasses of `Theme`.

> There are a lot of peculiarities about Theme. For example, pv.set_plot_theme('dark') does not make pv.global_theme an instance of DarkTheme.

Another variation of this is that you can have an instance of `DarkTheme` that gives the same behavior as `DocumentTheme`.  That is the `isinstance` check is totally meaningless.

I suggest that we instead make these objects, e.g. `dark_theme`, of the `Theme` class.  We can deprecate the classes.  This reduces the complexity greatly.
