### ISSUE TITLE
Error after updating sklearn to 1.1.1

### ISSUE THREAD

**Issue by jc-barreto** [pyvista/pyvista#2701]
### Describe the bug, what's wrong, and what you expected.

I was running pyvista just fine, but I needed to update sklearn, and now, when I try to plot with pyvista I got the error: "AttributeError: module 'orjson' has no attribute 'dumps' " I don't know how to fix it. I have tried to delete the jason file, as mentioned [here](https://stackoverflow.com/questions/11369734/python-json-module-has-no-attribute-dumps), but didn't work.

### Steps to reproduce the bug.

```python 

import rasterio
import gemgis as gg
import pyvista as pv
pv.global_theme.jupyter_backend = 'ipyvtklink'
import numpy as np
import os
import matplotlib.pyplot as plt
from rasterio.plot import show
import seaborn as sns
import os
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import scipy
import matplotlib.colors as colors

mesh = gg.visualization.read_raster(path=file_path + 'topo_elev.tif',
                                    nodata_val=9999.0,
                                    name='Elevation [m]')
topo_pv = mesh.warp_by_scalar(scalars="Elevation [m]")

sargs = dict(fmt="%.0f", color='black',title='Elevation')

p = pv.Plotter(notebook=True)
p.add_mesh(mesh=topo_pv, scalar_bar_args=sargs, clim=[1210, 1320])
p.set_scale(1,1,1)
p.set_background('white')
p.show_grid(color='black')

p.show()
 ```

### System Information

```shell
Date: Thu May 26 11:11:00 2022 Hora de Verão de GMT

                OS : Windows
            CPU(s) : 12
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.8 GiB
       Environment : Jupyter
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics 630
       GPU Version : 4.5.0 - Build 24.20.100.6292

  Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46)
  [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.34.0
               vtk : 9.1.0
             numpy : 1.22.4
           imageio : 2.19.2
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
             PyQt5 : 5.12.3
           IPython : 8.3.0
          colorcet : 3.0.0
        ipyvtklink : 0.2.2
             scipy : 1.8.0
        itkwidgets : 0.32.0
              tqdm : 4.62.3
```

### Screenshots

![image](https://user-images.githubusercontent.com/42352209/170467612-ab29a0d5-04a3-4eb1-a3da-2c2c8a08e280.png)
![image](https://user-images.githubusercontent.com/42352209/170467658-d0d257cc-fb63-4b02-b6c4-b69014107aee.png)
![image](https://user-images.githubusercontent.com/42352209/170467686-5fa81fcc-3129-4969-bc6e-5c5817dc9173.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
