### PR TITLE
MAINT: pydocstyle update

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR triggers the CIs to check the result of `pydocstyle` since the new version 5.0.0 is released.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I can reproduce Travis failure encountered in #486 on [master](https://travis-ci.org/pyvista/pyvista/jobs/622702564#L768):
```
AttributeError: 'ClassDef' object has no attribute 'args'
```

Let's use version `4.0.1` of `pydocstyle` to mitigate this while waiting for a fix.

**Comment by akaszynski** [comment]
Also noticing the same error for other PRs.

**Comment by GuillaumeFavelier** [comment]
Feel free to merge if you're satisfied by the hotfix.

**Comment by banesullivan** [comment]
Thanks @GuillaumeFavelier
