### PR TITLE
Read the scalar bar lookup table without the snake_case alias

### LINKED ISSUE #8990: Integration test failure
### Integration Test Failure

**Date:** 2026-08-29
**Run:** https://github.com/pyvista/pyvista/actions/runs/33266612390
**Ref:** `refs/heads/main`
**Commit:** [`fd260bfc`](https://github.com/pyvista/pyvista/commit/fd260bfce75fee8519d2bd65dbafb15f84698262) — Add 'cmap', 'clim', and 'lookup_table' parameters to Plotter.add_scalar_bar (#8449)

**Failing integrations:**
- [`cvista`](https://github.com/pyvista/pyvista/actions/runs/33266612390/job/99137672611) — @akaszynski

@akaszynski please take a look.

### PR DESCRIPTION
**Pull request by akaszynski**
### Summary

Fixes the nightly `cvista` integration failure in #8990, introduced by #8449.

```
FAILED tests/plotting/test_plotting.py::test_plot_add_scalar_bar_cmap
FAILED tests/plotting/test_plotting.py::test_plot_add_scalar_bar_lookup_table
E   AttributeError: 'cvista.vtkRenderingAnnotation.vtkScalarBarActor' object has no attribute 'lookup_table'
```

Both tests reached for `pl.scalar_bar.lookup_table` behind
`if pv.vtk_version_info >= (9, 4, 0):`. That guard was standing in for *"does the
snake_case wrapper exist"*, and version is the wrong proxy for it: cvista reports
9.7, so the guard opens, but cvista omits the snake_case API altogether (the same
divergence `NO_SNAKE_CASE` covers elsewhere).

### Changes

`pl.scalar_bar` is a bare scalar bar actor with no PyVista wrapper, so read the
table back the way `scalar_bars.py` itself already writes it — it calls
`SetLookupTable` on this same actor in two places. `GetLookupTable()` is present
on every supported build and returns the same `pyvista.LookupTable` object on
each, so the version guard goes away entirely.

I deliberately did **not** reach for
`@pytest.mark.skip_vtk_backend('cvista', reason=NO_SNAKE_CASE)`. These tests are
not *about* the snake_case API and they carry image baselines; skipping them
would drop scalar-bar render coverage on cvista, which is the backend most likely
to regress it.

### Testing

Drove both assertions directly on three builds:

| build | before | after |
| --- | --- | --- |
| cvista 9.7 | `AttributeError` | pass |
| stock VTK 9.7 | pass | pass |
| stock VTK 9.3.1 | *assertion skipped* | pass |

The last row is a small gain: the `>= (9, 4, 0)` guard meant the oldest supported
VTK never checked that the colormap actually reached the scalar bar.

`pre-commit` passes on the changed file.

Note: this PR carries the `integration-testing` label so the cvista job actually
runs here. Without it the `Integration` job is skipped on pull requests, which is
how #8449 merged green and still broke the nightly.

Closes #8990

### Agent disclosure

Diagnosed and written by a coding agent (Claude Code) at my direction; I have
reviewed it.

### CODE REVIEW

File: tests/plotting/test_plotting.py [hunk 1]
```diff
@@ -1065,9 +1065,11 @@ def test_plot_add_scalar_bar_cmap(verify_image_cache):
     cmap = 'bwr'
     pl.add_scalar_bar(cmap=cmap)
 
-    # pl.scalar_bar is a vtkScalarBarActor for vtk < 9.4.0
-    if pv.vtk_version_info >= (9, 4, 0):
-        assert pl.scalar_bar.lookup_table.cmap.name == cmap
+    # ``pl.scalar_bar`` is a bare scalar bar actor with no PyVista wrapper, so read
+    # the table back the way ``scalar_bars.py`` itself writes it. The snake_case
+    # ``.lookup_table`` alias exists only on stock VTK >= 9.4, and never on cvista,
+    # which omits the snake_case API altogether.
```
Comment (user27182) [inline tests/plotting/test_plotting.py]:
```suggestion
```

**Review by user27182 — APPROVED** [review]
