### PR TITLE
Reset Renderer._actors to None on close instead of deleting it

### LINKED ISSUE #8419: `_actors` deleted on close and cannot be restored due to `_NoNewAttributesMixin`
After calling `plotter.close()`, accessing `renderer._actors` raises `AttributeError`:

```python
import pyvista as pv

pl = pv.Plotter()
pl.renderer._actors  # works fine
pl.close()
pl.renderer._actors  # AttributeError: 'Renderer' object has no attribute '_actors'
```

This breaks PyVista's own trame tests on `main`:

```
FAILED tests/plotting/jupyter/test_trame.py::test_trame[vue2]
FAILED tests/plotting/jupyter/test_trame.py::test_trame[vue3]
FAILED tests/plotting/jupyter/test_trame.py::test_trame_custom_menu_items[vue2]
FAILED tests/plotting/jupyter/test_trame.py::test_trame_custom_menu_items[vue3]
AttributeError: 'Renderer' object has no attribute '_actors'. Did you mean: 'actors'?
```

## Root cause

Two PRs interacted:

1. **#7184** added `del self._actors` in `Renderer.deep_clean()` to release the `vtkPropCollection` reference on close.
2. **#7716** added `_NoNewAttributesMixin` to `Renderer`, which freezes attributes after `__init__`.

After `deep_clean()` deletes `_actors`, the attribute can't be restored because `_NoNewAttributesMixin` blocks new attribute creation. A `git bisect` confirms #7716 is the first bad commit.

## CI gap

This has been broken on `main` likely since July 2025 and went unnoticed. PyVista's trame CI (`integration-trame` tox env) only runs example scripts from `examples_trame/`. It doesn't execute the unit tests in `tests/plotting/jupyter/test_trame.py`. Those tests live in the main test suite but are gated behind `skip_plotting` + `skipif(not has_trame)`, so they only run on self-hosted GPU runners.

It was pytest-pyvista's integration CI (which runs the full PyVista test suite with trame installed) that caught the failure in https://github.com/pyvista/pytest-pyvista/pull/278

## Suggested fix

The simplest fix: set `self._actors = None` in `deep_clean()` instead of `del self._actors`. This releases the `vtkPropCollection` reference while keeping the attribute slot alive and avoiding the `_NoNewAttributesMixin` conflict. Code that accesses `_actors` after close would get a clear `AttributeError` on `None` operations rather than a confusing "object has no attribute" message.

Separately, it would be good to get `test_trame.py` running reliably in CI so regressions like this don't sit undetected for months.

### PR DESCRIPTION
**Pull request by gaoflow**
### Overview

Fixes #8419: after `plotter.close()`, accessing `renderer._actors` (or the public `renderer.actors`) raised `AttributeError: 'Renderer' object has no attribute '_actors'`.

```python
import pyvista as pv

pl = pv.Plotter()
pl.renderer._actors   # ok
pl.close()
pl.renderer._actors   # AttributeError  (before this PR)
```

### Root cause

As diagnosed in the issue (confirmed by `git bisect`):

1. #7184 added `del self._actors` in `Renderer.close()` to release the `vtkPropCollection` reference.
2. #7716 added `_NoNewAttributesMixin` to `Renderer`, freezing attributes after `__init__`.

Once `close()` deletes `_actors`, `_NoNewAttributesMixin` prevents the attribute from ever being re-created, so any later access raises `AttributeError`. `del self._actors` was the lone outlier — the surrounding lines in `close()` (`_bounding_box`, `_box_object`, `_marker_actor`, `_empty_str`) all reset to `None`, which is the pattern #7716 established precisely to avoid this.

### Fix

In `Renderer.close()`, set `self._actors = None` instead of `del self._actors`. This still releases the `_PropCollection` (and its `vtkPropCollection` reference), but keeps the attribute assignable. The `actors` property returns an empty dict when the renderer is closed, so it keeps working instead of raising:

```python
@property
def actors(self):
    if self._actors is None:
        # The renderer has been closed; it no longer holds any actors.
        return {}
    return dict(self._actors.items())
```

This follows the direction @user27182 endorsed in the issue ("set `self._actors = None`" / "set it to `{}` … would at least continue to work without raising any `AttributeError`"). I went with the backward-compatible `{}` behavior for the `actors` property; happy to switch to raising a "plotter is closed" error instead if that's preferred.

Note: this fixes the `_actors`-after-close `AttributeError` (the title of #8419). As @user27182 noted, the separate trame-test side effects (a `close_all()` interaction) are a distinct issue and are not addressed here.

### Verification

Added `tests/plotting/test_renderer.py::test_actors_after_close`: builds a plotter with a mesh, closes it, and asserts `renderer._actors is None` and `renderer.actors == {}` (both previously raised). Full `tests/plotting/test_renderer.py` passes (75 tests), and the close/clear/actor tests in `test_plotter.py` pass. `ruff check` / `ruff format` clean.

Fixes #8419.

### CODE REVIEW

**Comment by akaszynski** [comment]
FYI, I don't mind people using claude (Opus 4.7 is crazy good), but I'd appreciate a note that this PR was generated using claude. Not strictly necessary but nice to know. The gate here is if it works (and I appreciate that you're removing `del` as deleting attributes is an anti-pattern unless absolutely necessary.

Regardless, thanks for the contributions (and with the int32 as well, I've been patching that internally for a while in a closed source project that uses PyVista).

**Comment by binggao1230** [comment]
You're right, and happy to note it: yes, this PR was put together with Claude (Opus 4.7) — thanks for being upfront, and good to know you don't mind.

I just pushed fa94837 to fix the mypy failure: `_actors` is now typed `_PropCollection | None` (matching the sibling teardown attributes `_bounding_box`/`_box_object`/`_marker_actor`, which already follow the reset-to-None pattern), with the few reads of it guarded — `compute_bounds` and `remove_actor` go through the public `actors` property (which returns `{}` when closed) and `BackgroundRenderer.resize` early-returns when closed. The regression test now also asserts those paths don't raise post-close.

And fully agree on `del` being an anti-pattern once `_NoNewAttributesMixin` is in play. Thanks for the reviews on both this and the int32 PR!

**Review by banesullivan — APPROVED** [review]
