### PR TITLE
Add `self` annotations to dataset filters

### PR DESCRIPTION
**Pull request by user27182**
### Overview

There is a known typing issue with the dataset filters. It's a mixin class,  so `self` should be a dataset, but a dataset filter is expected. This generates a lot of type errors for undefined attributes or invalid args. See also https://github.com/pyvista/pyvista/issues/6279#issuecomment-2183191197.

One solution from #4774 is to use protocols. In fact, using a protocol class is _required_ by mypy for mixin classes to be typed correctly. See https://mypy.readthedocs.io/en/latest/more_types.html#mixin-classes. But, this requires a lot of restructuring. 

Instead, this PR proposes annotating `self` as needed, e.g. as vtkDataSet, MultiBlock, ImageData, whatever. This resolves all of the type errors. The caveat is that, since we aren't using protocols,  this annotation is itself a type error. So, this requires `# type: ignore[misc]`. It's not perfect, but this way we only need to ignore a single type error in the function signature, rather than a bunch of type errors in the function body.

### CODE REVIEW

**Comment by user27182** [comment]
Looking for some input from @MatthewFlamm and @akaszynski on this. Do you like the idea of annotating `self` as a dataset type to fix the attribute/arg type errors and use a single `# type: ignore[misc]` in the function signature instead?

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Review by tkoyama010 — CHANGES_REQUESTED** [review]
Waiting review of others.

File: pyvista/core/filters/data_set.py [hunk 1]
```diff
@@ -47,8 +48,10 @@
 class DataSetFilters:
     """A set of common filters that can be applied to any vtkDataSet."""
 
-    def _clip_with_function(
-        self,
+    points: pyvista.pyvista_ndarray
```
Comment (user27182) [inline pyvista/core/filters/data_set.py:51]: This line is needed to resolve a bunch of type errors caused by #5434.

If we remove this line, it generates errors like:
``` python
pyvista/core/filters/poly_data.py:2838: error: Cannot determine type of "points"  [has-type]
            np.apply_along_axis(f, 1, mesh.points)
```
``` python
pyvista/core/dataset.py:439: error: Signature of "points" incompatible with supertype "DataSetFilters"  [override]
        @property
         ^
pyvista/core/dataset.py:439: note:      Superclass:
pyvista/core/dataset.py:439: note:          ndarray[Any, dtype[floating[_32Bit]]]
pyvista/core/dataset.py:439: note:      Subclass:
pyvista/core/dataset.py:439: note:          pyvista_ndarray
```

It is a bit odd to have this type hint here though. Alternatively, we can remove it and simply `# type: ignore` the individual errors on a per-line basis.

Comment (user27182) [reply pyvista/core/filters/data_set.py]: The hint was removed in [d5ab232](https://github.com/pyvista/pyvista/pull/6870/commits/d5ab232c147dad2696251ad422fb2cf012a8fc3f) and type ignores added instead. This is better, because if https://github.com/pyvista/pyvista/issues/5434 ever gets fixed, then mypy should auto-detect that the ignores are no longer needed at that time. By contrast, if we keep the property's type hint we won't get notified by mypy that it's redundant (and we won't know to remove it later).

**Comment by akaszynski** [comment]
Tentative yes to your question, @user27182, but give me a bit to review. Cooking a turkey for the next few hours.

**Review by MatthewFlamm — APPROVED** [review]
I think it would be best long term to either make a protocol or redo the inheritance model (this would be my preference).  But in the meantime, it makes sense to me to type what the intention is, so I'm +1.

**Review by banesullivan — APPROVED** [review]
+1 for looking into better long term solutions to this inheritance model or moving towards Protocols. In the meantime, I think these type annotations are a great benefit

File: pyvista/core/filters/data_set.py [hunk 2]
```diff
@@ -1755,7 +1762,9 @@ def outline(self, generate_faces: bool = False, progress_bar: bool = False):
         _update_alg(alg, progress_bar, 'Producing an outline')
         return wrap(alg.GetOutputDataObject(0))
 
-    def outline_corners(self, factor=0.2, progress_bar: bool = False):
+    def outline_corners(  # type: ignore[misc]
+        self: _vtk.vtkDataSet | _vtk.vtkMultiBlockDataSet, factor=0.2, progress_bar: bool = False
```
Comment (user27182) [inline pyvista/core/filters/data_set.py:1766]: Adding a note here for completeness (not intended to block approval).

This is a tricky filter to type since the internal vtk filters allows vtkDataObject, not just vtkDataSet.
It would probably be better to use a new `ConcreteDataObjectType` type here (similar to `ConcreteDataSetType` added in https://github.com/pyvista/pyvista/pull/6854). Otherwise, if a `DataObject` is passed to this function a false positive type error will be generated (since `DataObject` does not inherit from `vtkDataObject`).

But, this would also (perhaps unfavorably) narrow the type to pyvista DataObjects only, even though in this case any vtkDataObject is allowed, resulting in false positive type errors for unwrapped vtk classes.

Perhaps it may be best to do `self: DataObject | vtkDataObject` and then wrap `self` in the filter. This general idea of typing `vtk | pyvista` inputs and wrapping `self` could apply to all filters. And it would help remove the use of `ConcreteDataSetType` or `ConcreteDataObjectType` as a type hint, which is good because this is more of an internal typing construct rather than something that users should have to think about.

These subtle typing changes can be made in a follow-up PR though. The main goal for this PR is to add initial annotations and get approval for the `type: ignore[misc]` idea generally.

**Review by banesullivan — APPROVED** [review]

**Review by tkoyama010 — APPROVED** [review]
