### ISSUE TITLE
`_actors` deleted on close and cannot be restored due to `_NoNewAttributesMixin`

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#8419]
After calling `plotter.close()`, accessing `renderer._actors` raises `AttributeError`:

```python
import pyvista as pv

pl = pv.Plotter()
pl.renderer._actors  # works fine
pl.close()
pl.renderer._actors  # AttributeError: 'Renderer' object has no attribute '_actors'
```

This breaks PyVista's own trame tests on `main`:

```
FAILED tests/plotting/jupyter/test_trame.py::test_trame[vue2]
FAILED tests/plotting/jupyter/test_trame.py::test_trame[vue3]
FAILED tests/plotting/jupyter/test_trame.py::test_trame_custom_menu_items[vue2]
FAILED tests/plotting/jupyter/test_trame.py::test_trame_custom_menu_items[vue3]
AttributeError: 'Renderer' object has no attribute '_actors'. Did you mean: 'actors'?
```

## Root cause

Two PRs interacted:

1. **#7184** added `del self._actors` in `Renderer.deep_clean()` to release the `vtkPropCollection` reference on close.
2. **#7716** added `_NoNewAttributesMixin` to `Renderer`, which freezes attributes after `__init__`.

After `deep_clean()` deletes `_actors`, the attribute can't be restored because `_NoNewAttributesMixin` blocks new attribute creation. A `git bisect` confirms #7716 is the first bad commit.

## CI gap

This has been broken on `main` likely since July 2025 and went unnoticed. PyVista's trame CI (`integration-trame` tox env) only runs example scripts from `examples_trame/`. It doesn't execute the unit tests in `tests/plotting/jupyter/test_trame.py`. Those tests live in the main test suite but are gated behind `skip_plotting` + `skipif(not has_trame)`, so they only run on self-hosted GPU runners.

It was pytest-pyvista's integration CI (which runs the full PyVista test suite with trame installed) that caught the failure in https://github.com/pyvista/pytest-pyvista/pull/278

## Suggested fix

The simplest fix: set `self._actors = None` in `deep_clean()` instead of `del self._actors`. This releases the `vtkPropCollection` reference while keeping the attribute slot alive and avoiding the `_NoNewAttributesMixin` conflict. Code that accesses `_actors` after close would get a clear `AttributeError` on `None` operations rather than a confusing "object has no attribute" message.

Separately, it would be good to get `test_trame.py` running reliably in CI so regressions like this don't sit undetected for months.

**Comment by edabor** [comment]
> This has been broken on main likely since July 2025 and went unnoticed. PyVista's trame CI (integration-trame tox env) only runs example scripts from examples_trame/. It doesn't execute the unit tests in tests/plotting/jupyter/test_trame.py. Those tests live in the main test suite but are gated behind skip_plotting + skipif(not has_trame), so they only run on self-hosted GPU runners.

> Separately, it would be good to get test_trame.py running reliably in CI so regressions like this don't sit undetected for months.

Maybe I'm missing something, but the tests for which you see failures are **not** skipped in the `pyvista` CI, see the log for all supported platforms:
- **windows**: https://github.com/pyvista/pyvista/actions/runs/23579469969/job/68659401995#step:8:248
- **linux**: https://github.com/pyvista/pyvista/actions/runs/23579469969/job/68659145962#step:8:1132
- **macos**: https://github.com/pyvista/pyvista/actions/runs/23579469969/job/68660127331#step:8:111

**Comment by user27182** [comment]
Some comments:
- Using `del self._actors` in https://github.com/pyvista/pyvista/pull/7184 was a poor choice, and was following an existing design patter where new attributes were dynamically added to the plotter and then deleted later. 
- Adding the `NoNewAttrMixin` class https://github.com/pyvista/pyvista/pull/7716 highlighted a lot of issues with dynamically creating and deleting variables, and that PR actually fixed a lot of these by setting these variables explicitly to `None` in `__init__`, and setting them to `None` again later as needed instead of using `del`. But alas the use of `del self._actors` was missed.
- Other `AttributeError` issues relating to deleting attributes are also still popping up, e.g. #8395 

I agree with this fix in principle:
> The simplest fix: set self._actors = None in deep_clean() instead of del self._actors. This releases the vtkPropCollection reference while keeping the attribute slot alive and avoiding the _NoNewAttributesMixin conflict. Code that accesses _actors after close would get a clear AttributeError on None operations rather than a confusing "object has no attribute" message.

But IMO since you're still getting `AttributeError`, I'm not so sure that the issue is clear. Users might still ask, by why is `actors` None? And the real reason is that the plotter is closed. So maybe raising `ValueError: Plotter is closed and has no actors` is a better solution.
Or maybe even set it to `{}`, depending on what we want to convey, since `None` could mean "plotter is closed". But an empty dict would at least continue to work without raising any `AttributeError`.

But, based on the investigation and discussion from from https://github.com/pyvista/pytest-pyvista/pull/278#issuecomment-4134651202, I don't think resolving this issue (#8419), will actually solve this problem:

```
FAILED tests/plotting/jupyter/test_trame.py::test_trame[vue2]
FAILED tests/plotting/jupyter/test_trame.py::test_trame[vue3]
FAILED tests/plotting/jupyter/test_trame.py::test_trame_custom_menu_items[vue2]
FAILED tests/plotting/jupyter/test_trame.py::test_trame_custom_menu_items[vue3]
AttributeError: 'Renderer' object has no attribute '_actors'. Did you mean: 'actors'?
```

Because the real issue seems to be that there are side-effects from calling `pv.close_all()` inside a trame context, such that closing the plotter for one test somehow closes the plotter for the other test, even though these tests are supposed to run independently.

So even if we return `{}` to fix the access to `actors`, the problem remains that the plotter for the test was unexpectedly closed, and hence is still likely to fail anyway, just not from `AttributeError`.

**Comment by user27182** [comment]
> > This has been broken on main likely since July 2025 and went unnoticed. PyVista's trame CI (integration-trame tox env) only runs example scripts from examples_trame/. It doesn't execute the unit tests in tests/plotting/jupyter/test_trame.py. Those tests live in the main test suite but are gated behind skip_plotting + skipif(not has_trame), so they only run on self-hosted GPU runners.
> 
> > Separately, it would be good to get test_trame.py running reliably in CI so regressions like this don't sit undetected for months.
> 
> Maybe I'm missing something, but the tests for which you see failures are **not** skipped in the `pyvista` CI, see the log for all supported platforms:
> 
> * **windows**: https://github.com/pyvista/pyvista/actions/runs/23579469969/job/68659401995#step:8:248
> * **linux**: https://github.com/pyvista/pyvista/actions/runs/23579469969/job/68659145962#step:8:1132
> * **macos**: https://github.com/pyvista/pyvista/actions/runs/23579469969/job/68660127331#step:8:111

Indeed the tests are running. The issue isn't that the tests aren't running, it's that https://github.com/pyvista/pytest-pyvista/pull/278 adds a fixture to call `pv.close_all()` for trame tests, whereas it seems this auto-close fixture is not currently being used by the pyvista tests.

And so it's more of a CI gap where `trame` tests don't currently close all plotters, and if they do, we're seeing side effects where closing the plotter from one test is somehow closing the plotter for a second, unrelated test. To me this reveals either a testing issue with our CI, or an implementation issue with the trame plotter somehow sharing variables or instances.

**Comment by banesullivan** [comment]
Excellent digging! Sorry I didn't catch that... was trying to wrap my head around all of it late into the night. This may be an implementation issue with our trame wrapping... I'll dig into this a bit more tonight
